#166575772 add a reusable input component
andela/ah-kgl-wakanda-frontend pull request #10
Opened 2019-06-10 20:38 UTC by dusmel

#### What does this PR do?
This PR will add a flexible and customizable input component.

#### Description of Task to be completed?
• handle properties like required, types and placeholder
• comes with a built-in label support 
• support validation with clear messages ( The validation is triggered when the input loses focus)

#### How should this be manually tested?

| attribute  |  options | required  |
|--|--|-
| name | [value]  | true
| type | [text, email, password....]  | optional( default --> `text` )
| label | [value]  | optional
| required | [none, false]  | optional( default --> false )

#### Any background context you want to provide?

Most of the time the input is handled multiple times with a different design. 
Since inputs are going to be used extensively in the app it is logic and powerful to have a reusable component that is flexible and customizable hence the implementation of this chore.

#### What are the relevant pivotal tracker stories?
#166575772

#### Screenshots (if appropriate)
# 1
![image](https://user-images.githubusercontent.com/27511264/59224743-5f9b1180-8bcf-11e9-923d-fc755e045b90.png)

# 2
![image](https://user-images.githubusercontent.com/27511264/59224893-bd2f5e00-8bcf-11e9-822d-2c486003438e.png)

# 3
![image](https://user-images.githubusercontent.com/27511264/59224955-db955980-8bcf-11e9-9697-cbe0d43a31cd.png)

# 4
![image](https://user-images.githubusercontent.com/27511264/59224985-f071ed00-8bcf-11e9-8cc9-6530ba7af87e.png)

#### Questions:

N/A

2019-06-10 22:45 UTC, coolbeatz71 requested changes
Excellent work! @dusmel. Just one thing to take a look. In my opinion, putting the `orange` background on the `error message` doesn't look good. Once we get a lot of error messages on the form, It wouldn't look nice as the orange color will be dominant, thus probably bad for the user.

For example, If you could just put a red text, It will be sufficient and nice for the user.

Apart from the error message, everything else looks 👍👍👍

2019-06-11 07:40 UTC, Karlmusingo commented
Hey @dusmel, Your PT id should be a link to the Pivotal Tracker story.

2019-06-11 07:46 UTC, Karlmusingo approved these changes

2019-06-11 08:46 UTC, dusmel commented
> Excellent work! @dusmel. Just one thing to take a look. In my opinion, putting the `orange` background on the `error message` doesn't look good. Once we get a lot of error messages on the form, It wouldn't look nice as the orange color will be dominant, thus ugly.
> 
> For example, just a red text will be sufficient.
> 
> Apart from the error message, everything else looks 👍👍👍

@coolbeatz71 I get your point but the way the validation is designed it gives you the error as soon as the input loses the focus, so you will probably not have all of them at the same time

2019-06-11 08:53 UTC, gracelungu requested changes

2019-06-11 08:53 UTC, gracelungu commented on src/Components/Common/input/exemple.jsx
> +export default Form;
This example file is irrelevant, it is only needed in the development and should be removed after.

2019-06-11 08:53 UTC, gracelungu commented on src/Components/Common/input/input.jsx
> +// import { connect } from 'react-redux';
Commented codes should not be present. These serve no purpose in the implementation of the project.

2019-06-11 10:19 UTC, gracelungu approved these changes

2019-06-11 10:25 UTC, coolbeatz71 commented
> > Excellent work! @dusmel. Just one thing to take a look. In my opinion, putting the `orange` background on the `error message` doesn't look good. Once we get a lot of error messages on the form, It wouldn't look nice as the orange color will be dominant, thus ugly.
> > For example, just a red text will be sufficient.
> > Apart from the error message, everything else looks 👍👍👍
> 
> @coolbeatz71 I get your point but the way the validation is designed it gives you the error as soon as the input loses the focus, so you will probably not have all of them at the same time

Okay

2019-06-11 10:26 UTC, coolbeatz71 commented
> Excellent work! @dusmel. Just one thing to take a look. In my opinion, putting the `orange` background on the `error message` doesn't look good. Once we get a lot of error messages on the form, It wouldn't look nice as the orange color will be dominant, thus ugly.
> 
> For example, just a red text will be sufficient.
> 
> Apart from the error message, everything else looks 👍👍👍

Ok

2019-06-11 10:37 UTC, coolbeatz71 approved these changes

2019-06-11 11:10 UTC, dkam26 commented
@dusmel , well done! How come you didn't write tests for the component? Kindly write tests for the component!

2019-06-12 10:47 UTC, merged