Ch dropdown component design 166575854
andela/ah-kgl-wakanda-frontend pull request #12
Opened 2019-06-12 13:13 UTC by giseleiradu

#### What does this PR do?
- Creates a profile dropdown for the top nav

- Adds unit tests for the profile dropdown 

#### Description of Task to be completed?

- Import the component onto the top nav to use this component

- The component receives the profile attributes which are: the ```firstName```, the ```lastName```, and the picture which is a random avatar by default

#### How should this be manually tested?

- By ```npm test```

- By importing the ```ProfileDropdown``` and use it where it is needed

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

- #166575854

#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

2019-06-13 10:24 UTC, coolbeatz71 approved these changes
Good job! But this component requires refactoring:
     - it should be displayed only the user is logged in (For example)
 
Because it should be displayed in the navbar, we will need to pair program and refactor it later in the next sprint.
 
Apart from this concern, kindly follow the PR  convention:
 - make PT story ID clickable
 - fix houndci issues

2019-06-13 13:20 UTC, dusmel approved these changes

2019-06-13 13:22 UTC, dusmel requested changes
I just noticed hound error otherwise good work 👍

2019-06-14 14:06 UTC, dusmel approved these changes

2019-06-17 11:06 UTC, merged