#165020088 Like and Unlike an article
andela/ah-kgl-wakanda-frontend pull request #30
Opened 2019-07-02 10:36 UTC by gracelungu

#### What does this PR do?
This PR enables the user to like and unlike an article

#### Description of Task to be completed?
- Add the like and unlike actions
- Trigger the actions when liking or unlinking
- Write tests

#### How should this be manually tested?
On the single article page, once the like and unlike buttons are clicked, the article will be liked or unliked by the user.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

[#165020088](https://www.pivotaltracker.com/n/projects/2321845/stories/165020088)

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/46924450/60506390-ff772700-9cc5-11e9-85e4-dd85f179e87c.png)

#### Questions:

N/A

2019-07-02 10:43 UTC, Karlmusingo approved these changes

2019-07-03 09:32 UTC, giseleiradu reviewed
@gracelungu, I would like to know if we have an unlike or dislike in the application. Let me know the thumbs-up as well as the thumbs-down's role.

Otherwise, good job.

2019-07-03 12:55 UTC, dusmel requested changes
I can see that you have two buttons ( like and unlike ) how are you going to provide the number of people who unliked the article since we don't support that in the backend. I can see that you are just displaying a text beside the unlike button I am confused can you give more highlight about that

2019-07-05 09:47 UTC, gracelungu commented
> I can see that you have two buttons ( like and unlike ) how are you going to provide the number of people who unliked the article since we don't support that in the backend. I can see that you are just displaying a text beside the unlike button I am confused can you give more highlight about that

The problem has been resolved, only one button is present.

2019-07-05 09:50 UTC, dusmel approved these changes

2019-07-05 09:51 UTC, merged